# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/bitnami.com/sealedsecret_v1alpha1.json
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miniflux-admin-credential
  namespace: miniflux
spec:
  encryptedData:
    password: AgCkX+GnqVN06KBWcMotRAt9TTvUzg3w0Sxir4XsK3dGm2C6N2xVvw5IZJ0y1Y3YW9nIL0jafqpFetzg9SokSOYv5tyOrTD2j1FkzjyMQPQ1z6/c32zQ5EwvODiq+RbCCfDNNXe09JW36Z40FQlcncT9MifdKPLRod/BFFLXEavxYXvOZQhsndDAzmOh5X/kSwua76k1gq1RD6iXLJ6PE76ziGvSuq+noEbbiYf1sY/Zn2w7UrY9Aa/sQBuDnnPKv3ihCbay/iTjWskS5mJzr6XKsiFFb49b8CQ4ML6U4xb6ZUiFVEOI3z/qphr2I1jDNSG+u/H/9xsSLRXW3n06RPIm47iIu+oT6kNC81ZFJVl/o+7axlkP5gxtF7HTqEVwBUa5zleJKpXZTftSroyikyLjZcp4Y3w11IdqBLXjG7sUrxbt9DCav5IN8f6kfsLG+ZRfh2Q9tbGtU4NsbkEqtltCo4P/JM0WZ0Plc/gmcZNGWZjjiDiBp0WMhnVB/+pTRnFAG8Bg6hYNtQz1r+9IyDBP9jcMvhhhXmNzAYZew5DXZYxU/GEhyLwcadCtEHiwD9/VQ/wMYXNJ8hYETHq51U9YXXPTzOrhIZBqSJJ28wZof+LA4DDnyhIq+9dIm6afJ+sa2TFpPmJKVTc1vczC+SPJyn+Fxx9FvOr0s+HGuY3ngvuIO8gzUCmkm2QTNcaA13NIfziICwZMbpt2b+39XYW+8gQW85n9sZE3obh5ER8=
    username: AgCDdJ7J0tATBDo/5XohQ9nJudY8KDsSGs03n6BzeQfJzL+fq3HQlwOc8DRYhw9eu4oQY/2dvPFR97uZodFMeNVUrQ6WjpH51vttvmV0G3GJYuIa+eU6D6eCR5KblHw1ftEpDp5av+AaGmXvyKmDvKf0B5s1wPPf4p5eLz+1hleLe1RnvQivOPC8wOMdi5Ba05stQHdXX6kuZl+7SB4kAEHPRtlizCiByYQkNK3eA/+AsfJoZl5OdDOYW70x+fH7YGnplHpOYlMVmKFqRUJfdbSbqnBIzu0dJpxDQaXqWay+1PXaqlXDBrEvsX+sYNJn6OomAi4dRAi0GiKpjxBKD1078vHDBQvIdttYjQIdKzgXKyYL9mKVrLlHLbo2JQpYO5GAZtbhXmoetx9q7bbcNmBvYS1dAEIz1lPPtjzgB0HZgIDnoCTBGHMFUOHOBCFqrJoOzguqc5+FfRifUI/SsyrvdPSOmTKI8MtDgHCnr+/4NrbQ9wTlsdgnam0HxO0UFpo9ZewVWrw8tlPBmms7WP7KW2ZVcVPQh9T6rsGHvRkkfzyp7+JrzMndMiKwSK2soOFHJOqhpUH7pbiAXp5+nbK70QceW3dj2L2LbJjiqV2F5koC2mb8j1DEKqo3MU7LwSi1uAEfGVxGvyfX1SLaIwll8qkOSHi5EikvE7Db+pR3d0Nx5c05EEvDERVIUT+y5ILMCbw4Kkyc
  template:
    metadata:
      name: miniflux-admin-credential
      namespace: miniflux
    type: Opaque
