apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miniflux-admin-credential
  namespace: miniflux
spec:
  encryptedData:
    password: AgCst0aXaAsJkN8CpuD1LCiT2PZJcwkY0L936cjRukdPg0m11RDd6CUJnwB8KTx2BkEiBMf69+u2pquthKp5m79E5oqZ8+K280DpnSAQmUOlO7YJAAPw9AsnnQeP9YlLznCMvpMaCUw1BndcK0iCvE3uesNWjf4IW0JpwBHvS0BguHDhelnZcgaQMb6xO1EBU8CC5YIx0ZyNifV7PqQ7RgeXl2lLhea102TYO8mkwiPp8DxBT3E+3uQBR7keqtwgIdgDdl9oYgDxQCMddc6575ZBZbSo699w8G4y7+rkyJWo6qTU8ym24fi2q2Zd1wT9EUg4XX53G4Mm1BUOCW6rH4Uu73SugCAf5oAcevZN3751yelgc4jIDVc25fwe8Awi+H3A8csh17y38RXvB6GAahk4iRU18duLmzVvuZQfd5+l4gt3nCvOdXgSwKMFdtojE6oyHRT8dr+UFMeZLYR7sJed6AVw/apGk6Rd8eDGx1IcuyKiEhDo+2Mn3xo460HAuzphvUsrei6ERU1ov/hJ2kJopuw+k1hqpA8hA5l2NXaTn3Pj4SggZ2DDmFKcfbDzvCc57feshqN39sH8NLLOnTQgp/LONCekWDIV2Z+4ofJ7eN5z+9L0w/+NRB5GZpYDd6XuI5nY0z/8QHazN5iIxPiET5oljG0fBW8dAJ3QL+8Oa0aiCK10x9xEbkS0HFDwTj1TyQZsbGT/xgzNJCqh+KjC+rJP7Qolh4B5SqG4jmg=
    username: AgA+x+uEXRPYjU87yeIZN1fYGpQuUZ6sk3RiLdjIauAzv12cVoZEVhGe4gxWZWvVOFir5mWFUUJszyd76IXqtiEaQb9BhJZMeNj2qj8Im5rx0/OmxJd76BR6Zy+KjZfTXzLG/zylOQ3vtbo+U8D7FinjADaHvtxj65JepZNh6nBW+ZfFVBKiHlgs8WJtO3vx3LCJkVGiHY9tVVdezX8wmeXBakTudv2PdZbO0X/6CMSgsxxsavZTZiS99bjlsMaEQ4e6VtIg+2sp4T1m4UxddgK9X75qkv+KTzt3hvlyMBexv779YynkmWKK2i9jGM/6Wm+RlNKLombq3Mzc+Lx5mLMWcSWbw7+hdmKoEDc7uYTVI5y1Y2t3XlXTyUm5keCS9OKOdMsSSqa00GnGlfLNpYvm/Q1uSc0vPumA4clPmwjqVbk5Ejj9ur3wLKWpRIEZ1Xsk4209/2xlTPx9upmaAEvHBZ4UkL2yS75Xa+IoszOth6XnnW6lECao2aZlZPVDvJhMPQO6WW4ef6tB3XsuM15G8vNO2zbMN0HXSSbTjHtI24UHZ9dpE2try96fvaiqy/4ws47BPMJ7d9TY+T9lGfvsBnG50QY+4J6LmQNjuSxy5B8eUakfrHNKuJJpgV4SsIGZ25jkblPaNAS9MX4eER1bl6+0lg1QbFGPXfwzKfmRysKe9jZ1uf4ovMhA4T8YlwBk7Qb2TA==
  template:
    metadata:
      name: miniflux-admin-credential
      namespace: miniflux
    type: Opaque
