# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/bitnami.com/sealedsecret_v1alpha1.json
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-users
spec:
  encryptedData:
    NTFY_AUTH_USERS: AgBmYqBrwjymdCSLL+qdFrbplaPSqgZG8C1G45XiyMY2nW8jON+f5eK9MB6YyphYwC3kSALTP/9JDM3NxaCxr0VQNBMvjjvfy/XsZls4caZ1o5W3zVcPNc3Br1WOYZgsI9Gq3qd3kwoNVLQB4gX2N+dHdawCNXycnV+izQAg/TdA6bouMtsHjsr45/RKpPPKwUsyWxaxVE9u8oX8ztXCu3TXUC6ge2woyF0/+m0g9Jx3dwrdXvf799bO8HtOs6K3sG4l6kRu9hzM1rfpt63tLVBEn+DfNdqS/hGdQuDB4JCMDa+5x0/PVi4LtZEe1W/hPDIV3wDzQ4DCtY3AuW1qVf+/0Fd4yoMc6Q5RgELJEN086YJsUtuhT0M10KdK84eq5aXnbJM9lBJQLCCDclHxmUMa0M3kWuwIfBCoWbkuUmHaygVbNVa+58rF+fE8e07SEKY17DSNIC9EaUbgSHcBxvTv9Gnkk8Tc5pZX0nQ4lSrVXTsDoLbDT7FNsJ5rJj7E4rnLmfY/pwvOSYt0AINIyLkmKsaFjlPtU2i0pcXaT+06g5Vu/RouOloPeVSPoJ94qD9S3hi58SDz6GnzGzy5XE/6RxBg6UHCDJDzVnXb/LjyjL22C9Ift07vEUfcHvoipgaMOLYLLx31xSsa6ynEG7/Spltnz6Kc5FiR8BTY/arggPm4tYhybuw0kJYHx86qHLuOCg520E5hX+bhuPB2ux9CvsbI9Pj4B3YqtqRHgYSCQ5QxPs1WrSGT0KhmskzCc0lDflN/62qZJFHxZ5INl93pFzO5g3OZYvybcrU0j5M1EyocYAUVGjQFTBdAGnoH85I+Jcald10+eGXm9Pkzuk4jEoGT5ZZqnqZia54iCFdFsVuw8NQxaDt2ifoV1CVkWxI2ZP6xfGiWIzMdjuHnK2ueOnLqthIxCCZjYfEKxH482hzdArihxB/XgVW253fIwLuPWECaJx7E5shF7ZuXNAhRtgoGVV2ZIGXThFWfoMBS3DVX6M5t
  template:
    metadata:
      name: ntfy-users
    type: Opaque
