# yaml-language-server: $schema=https://github.com/datreeio/CRDs-catalog/raw/refs/heads/main/bitnami.com/sealedsecret_v1alpha1.json
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ntfy-users
spec:
  encryptedData:
    NTFY_AUTH_USERS: AgCrnPV1j/XkbK5ZTaMRmLDtHjHU3ofXlzddUDEg7DwqAQY+O21kb0oAEq0O3bTV7/s5K3cFf3yjsey5otlK5TgszrTh39qE/p6CbdNARrRuNN94kziNG6KPAXRHo2fqVPkR35F2xLAEC89nM5PrYc0WUacUvgA+7jsGcM4ksZJfTT+IZe+A7YUbEngZ2r90pAekCS2xBdsZPXCazykdOxD841r83GJoRy5rhEaBlfCLa3y9lrek6dnYlgfykvR0KEzNu2BXJkDPat3HF2byf4b6okf5jcEeEgGRjIf5wH/f0aL4zEyrC28XHhX24w7oa9LD4fp87HtVW+msb8BMGwuDYH96p/rkZ5+/vPRTqbBc2EequKQA34JRGvQF92KxkFS/QT5G9wBUj/DlHy8yGpoq9RFL9IapXFauQjnwDfD8/V8wqXh+qgJaUFRdrp49x/qmn2D/0ysVyhUtR2GT5GhTfPEV9seqfscClZTS6gKq9q/odrXUkPBZpn1rBbNrtRhn/1Xa1OwG6LbUlELLhEfpq0RJ+FiVlT1fmMPzb0RnQItunXuNHTLJ3d0MpKuIw+KSom+AgWixotqxmFjWS5d6n4RiZTLXtdDpi5uuAOUyHmHFefMQ3IP/+tIE9zbi82POkyHxvVaRGwxSErWSrOavuTBR+3IIHyEFXrL+hrzDq2KqjUnLy+QrqPOldm9KnhacosrxLNpSRHHk6bKV7+fiCVOZd6PBLShI7ErNmwIou/34O9pRj+PWJeAvDq9JxXlkXeGOdWytxsHUBpJtQY53581m5C0sNTXkk0IAUfBXlhkOVylGWbb+Icitgu3dyV2vDdJ03+snSAXlJvBkEC5/YOvt2HWI3HBo2JUnxzgdjphMNLXAQeNTQjcvWqt93VuJ0L7XzVJwQhMn
  template:
    metadata:
      name: ntfy-users
    type: Opaque
