# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: databases
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
      namespace: flux-system
  interval: 1m
  path: ./kubernetes/databases/homelab
  prune: true
  wait: true
  retryInterval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
