apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-user-credential
  namespace: cnpg-system
spec:
  encryptedData:
    password: AgA9RsziGzjXIpJsnguB8UpLDSDHACjF5T2p1SuhjHxktxa9XPNRGBxS7pEg0zHWWrutsbEzg2+FhdWM/YFFvjJ+kF1boiP/Bf+PbFw+9kKiApr8yFNeJ28uHUWgRSq0WDmVD3WQV8q5drGcN0FTw+pTGIKliJnNlhJXwPXVXQVeTBhRB2li4Ym3XpmJnX+TSaPxqIOdH/9Y1Wp5V7fdbz73r4A8KM4gAB6XZRx8+9vq0sYI/LwS7rFMS/DgDYqmAaiyVbfEY2H+X8mQwhMNHcrvEbBkg2vYuZGcNhxkzToJv8tWYDqytT0JvqLm9MuHBHI9jNg/8MrRayepQP21PnWg5QYOwlRZeyYde0TMkSuSmQimzE3MRya/2ppjEeZXn9mLGj3d3BauusraI2ICIQJbEFDwPB2JYCzyxMIVyZGJ6h+traFhBUWbYWxlQjYwjrmjDVPLZd8SRDcGCHj51BHnDWWDpDW7k5zrgm/sZl6tQC9I1ZbxMkWHB1a8hD3S4UhkhH4szEetIBW9OeCNRZdU/XkL1voFpMLCDSdVFmv2FV9WeSGstQXWLv352YP0tOgnOn34d/v4ob3UN+HWm8MTGzN1HgB8FFFs4wHZ0wFA4ienNsuIw44PtnSg5zAFlgZHSVt5Q81YnIhKqrT0dfjUxtg95J0GyTyHIa4F2sG6DEOCPOBVPbDeATkH2ZCcAuYdjr5yzWBfn6p/kg6DpYKAJjF90+SvK1iALlXqpkxBkr2PfOmazJo=
    username: AgA5jpkgitmtWHuv9+XtuTEnWDg4Mb6pZ3oVyBdfTMKpgHufwtFXRTijfSGhfYrNnmqMvvn+k/oUICpC7IXS4e3fuixQXKoxRBxHd7gjUm6MocUsfpsnIhm8I8UPkpGWRlViPu4tirQTQNzX/Quh6qxERKoNKneLF66M8oadaH4kNBYZnDOAyooFiZpRCIL2dbxfoSMPXmH/a2c5gVNbL2msxFbz0Xym91XbHk1b8M8zv+s9zSBiLfANFqT+Vqrr04dC0dfyUzggCI2R/Yu5hVfDELKqmqKhonAP9v61ZuycqzfmmYeT4urDOdGAOyKOtQT2pUFtbtNkywBhK2FP4AiGKb7v028pB1X0gZAipyskRZl7og0z8qXJq+K6TkuHE3Q9e70TvE4RqGWiy3BCGoSvZIkjzMuXIYi/lNO4C+Jp4M0+GIPcONpG3C1LpZylCQvxqfXxHmuOtD0uOF5h7wYUGOZgjufGv30auPStBh+sUu1lQmPx9kOXqWuqsSp8popa30gkpbssF/r4uRiCKv30Hdzn5CUshLQhWssAB9/Xf75LpfWEz68uA9nj+cnlsUXSu+SR3aiDuJqSX/3Mvbn2sjpYxJeMw9QEqOyNk3/kbcRPReSNuvrTIYOIv8MZCfjKbzHCJFocb4RENjeXUXxMZk/UX1hkx55UQ4cbcOo3vzRUBa5OKlSzKrYwv+tYEJqofmA=
  template:
    metadata:
      name: n8n-user-credential
      namespace: cnpg-system
    type: kubernetes.io/basic-auth
