apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-default
  namespace: cnpg-system
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: default
  podMetricsEndpoints:
    - port: metrics
